name: Build Nginx Quic
run-name: ${{ github.actor }} is building Nginx Quic using GitHub Actions 🚀
on: [push]
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - run: sudo apt update && sudo apt install -y git gcc make autoconf libtool perl
      - run: git clone -b v3.6.1 https://github.com/libressl-portable/portable.git libressl
      - run: cd libressl && ls -al
      - run: ./autogen.sh && ./configure && make check && sudo make install
      - run: echo "Build libressl done ."